export type ReviewLocale = "en" | "tr" | "de" | "es" | "fr" | "hi" | "zh"

type ReviewCopy = {
  homeEyebrow: string; homeExplore: string; homeExample: string; homeExampleNote: string
  homeBoundaries: string; homeHow: string; homePrivacy: string; homeStart?: string; homeStartTitle?: string; homeStartText?: string; inspect?: string
  uaSent: string; uaMozilla: string; uaChrome: string; uaPlatform: string
  networkInterpret: string; networkNote: string
  greenMeasure: string; greenNote: string
  secStep1: string; secStep2: string; secStep3: string
}

export const reviewCopy: Record<ReviewLocale, ReviewCopy> = {
  tr: {
    homeEyebrow: "HTTP gözlemleme aracı", homeExplore: "Araçları keşfet", homeExample: "Örnek tarayıcı isteği", homeExampleNote: "Sunucu, isteği işlerken bu tür sinyalleri görebilir. Her satırı seçip ne anlama geldiğini inceleyebilirsiniz.", homeBoundaries: "Gördüğünüz verinin sınırlarını bilin", homeHow: "Headerly nasıl çalışır?", homePrivacy: "Gizlilik açıklamasını okuyun", uaSent: "Gönderilen metin", uaMozilla: "gerçek tarayıcının Mozilla olduğu anlamına gelmez; tarihsel uyumluluk ifadesidir.", uaChrome: "tarayıcı sürümü için bir sinyaldir, doğrulanmış kimlik değildir.", uaPlatform: "platform bilgisini belirtir; cihazın sahibi hakkında bilgi vermez.", networkInterpret: "Bu bilgileri nasıl yorumlamalı?", networkNote: "Değerlerin kaynağı ve kesinliği aynı değildir. Proxy, VPN, mobil ağ ve CDN kullanımı sonucu değiştirebilir.", greenMeasure: "Sonuç neyi ölçüyor?", greenNote: "Bu araç bir web sayfasının tamamını laboratuvar koşullarında ölçmez. İki ayrı sinyali yan yana gösterir.", secStep1: "Yanıtı al", secStep2: "Bulguyu sınıflandır", secStep3: "Düzeltmeyi doğrula"
  },
  en: {
    homeEyebrow: "HTTP observation tool", homeExplore: "Explore the tools", homeExample: "Example browser request", homeExampleNote: "A server may see signals like these while processing a request. Select a row to learn what it means.", homeBoundaries: "Understand the limits of what you see", homeHow: "How Headerly works", homePrivacy: "Read the privacy explanation", uaSent: "Sent string", uaMozilla: "does not mean the browser is Mozilla; it is a historical compatibility token.", uaChrome: "is a browser-version signal, not verified identity.", uaPlatform: "describes a platform signal; it says nothing about who owns the device.", networkInterpret: "How should you interpret this information?", networkNote: "These values do not have the same source or certainty. Proxies, VPNs, mobile networks and CDNs can change them.", greenMeasure: "What does this result measure?", greenNote: "This tool does not measure an entire webpage under laboratory conditions. It presents two limited signals.", secStep1: "Receive the response", secStep2: "Classify the finding", secStep3: "Verify the fix"
  },
  de: {
    homeEyebrow: "Werkzeug zur HTTP-Beobachtung", homeExplore: "Werkzeuge entdecken", homeExample: "Beispiel einer Browser-Anfrage", homeExampleNote: "Ein Server kann beim Verarbeiten einer Anfrage solche Signale sehen. Wählen Sie eine Zeile aus, um mehr zu erfahren.", homeBoundaries: "Die Grenzen der sichtbaren Daten verstehen", homeHow: "So funktioniert Headerly", homePrivacy: "Datenschutzerklärung lesen", uaSent: "Gesendete Zeichenfolge", uaMozilla: "bedeutet nicht, dass der Browser Mozilla ist; es handelt sich um ein historisches Kompatibilitäts-Token.", uaChrome: "ist ein Signal für die Browserversion, keine bestätigte Identität.", uaPlatform: "beschreibt ein Plattformsignal und sagt nichts über den Besitzer des Geräts aus.", networkInterpret: "Wie sind diese Informationen zu verstehen?", networkNote: "Diese Werte haben nicht dieselbe Quelle oder Genauigkeit. Proxy, VPN, Mobilfunk und CDN können sie verändern.", greenMeasure: "Was misst dieses Ergebnis?", greenNote: "Dieses Werkzeug misst keine vollständige Webseite unter Laborbedingungen, sondern zeigt zwei begrenzte Signale.", secStep1: "Antwort abrufen", secStep2: "Befund einordnen", secStep3: "Korrektur prüfen"
  },
  es: {
    homeEyebrow: "Herramienta de observación HTTP", homeExplore: "Explorar herramientas", homeExample: "Ejemplo de solicitud del navegador", homeExampleNote: "Un servidor puede ver señales como estas al procesar una solicitud. Selecciona una fila para saber qué significa.", homeBoundaries: "Conoce los límites de los datos visibles", homeHow: "Cómo funciona Headerly", homePrivacy: "Leer la explicación de privacidad", uaSent: "Cadena enviada", uaMozilla: "no significa que el navegador sea Mozilla; es un token histórico de compatibilidad.", uaChrome: "es una señal de la versión del navegador, no una identidad verificada.", uaPlatform: "describe una señal de plataforma; no indica quién es el propietario del dispositivo.", networkInterpret: "¿Cómo interpretar esta información?", networkNote: "Estos valores no tienen la misma fuente ni precisión. Un proxy, VPN, red móvil o CDN puede modificarlos.", greenMeasure: "¿Qué mide este resultado?", greenNote: "Esta herramienta no mide una página completa en condiciones de laboratorio; muestra dos señales limitadas.", secStep1: "Recibir la respuesta", secStep2: "Clasificar el hallazgo", secStep3: "Verificar la corrección"
  },
  fr: {
    homeEyebrow: "Outil d’observation HTTP", homeExplore: "Explorer les outils", homeExample: "Exemple de requête du navigateur", homeExampleNote: "Un serveur peut voir ce type de signal pendant le traitement d’une requête. Sélectionnez une ligne pour en comprendre le sens.", homeBoundaries: "Comprendre les limites des données visibles", homeHow: "Comment fonctionne Headerly", homePrivacy: "Lire l’explication sur la confidentialité", uaSent: "Chaîne envoyée", uaMozilla: "ne signifie pas que le navigateur est Mozilla ; c’est un jeton historique de compatibilité.", uaChrome: "est un signal de version du navigateur, pas une identité vérifiée.", uaPlatform: "décrit un signal de plateforme et n’indique pas le propriétaire de l’appareil.", networkInterpret: "Comment interpréter ces informations ?", networkNote: "Ces valeurs n’ont ni la même source ni la même précision. Un proxy, un VPN, un réseau mobile ou un CDN peut les modifier.", greenMeasure: "Que mesure ce résultat ?", greenNote: "Cet outil ne mesure pas une page entière en laboratoire ; il présente deux signaux limités.", secStep1: "Recevoir la réponse", secStep2: "Classer le résultat", secStep3: "Vérifier la correction"
  },
  hi: {
    homeEyebrow: "HTTP निरीक्षण टूल", homeExplore: "टूल देखें", homeExample: "ब्राउज़र अनुरोध का उदाहरण", homeExampleNote: "अनुरोध संसाधित करते समय सर्वर ऐसे संकेत देख सकता है। अर्थ जानने के लिए कोई पंक्ति चुनें।", homeBoundaries: "दिखने वाले डेटा की सीमाएँ समझें", homeHow: "Headerly कैसे काम करता है", homePrivacy: "गोपनीयता विवरण पढ़ें", uaSent: "भेजी गई स्ट्रिंग", uaMozilla: "का अर्थ यह नहीं कि ब्राउज़र Mozilla है; यह ऐतिहासिक संगतता टोकन है।", uaChrome: "ब्राउज़र संस्करण का संकेत है, सत्यापित पहचान नहीं।", uaPlatform: "प्लेटफ़ॉर्म का संकेत बताता है; डिवाइस के मालिक के बारे में कुछ नहीं बताता।", networkInterpret: "इस जानकारी को कैसे समझें?", networkNote: "इन मानों का स्रोत या निश्चितता समान नहीं है। Proxy, VPN, मोबाइल नेटवर्क और CDN इन्हें बदल सकते हैं।", greenMeasure: "यह परिणाम क्या मापता है?", greenNote: "यह टूल पूरी वेबसाइट को प्रयोगशाला परिस्थितियों में नहीं मापता; यह दो सीमित संकेत दिखाता है।", secStep1: "उत्तर प्राप्त करें", secStep2: "निष्कर्ष वर्गीकृत करें", secStep3: "सुधार की जाँच करें"
  },
  zh: {
    homeEyebrow: "HTTP 观察工具", homeExplore: "探索工具", homeExample: "浏览器请求示例", homeExampleNote: "服务器处理请求时可能看到这类信号。选择一行即可了解其含义。", homeBoundaries: "了解可见数据的边界", homeHow: "Headerly 如何工作", homePrivacy: "阅读隐私说明", uaSent: "发送的字符串", uaMozilla: "并不表示浏览器是 Mozilla；这是历史兼容性标记。", uaChrome: "是浏览器版本信号，而不是经过验证的身份。", uaPlatform: "描述平台信号，不代表设备所有者的信息。", networkInterpret: "如何理解这些信息？", networkNote: "这些值的来源和确定性并不相同。代理、VPN、移动网络和 CDN 都可能改变它们。", greenMeasure: "这个结果测量什么？", greenNote: "此工具不会在实验室条件下测量完整网页，而是展示两个有限的信号。", secStep1: "获取响应", secStep2: "分类发现", secStep3: "验证修复"
  }
}

export const reviewDetails: Record<ReviewLocale, {
  homeBoundaryText: string; homeHow: string; homePrivacy: string
  networkIp: string; networkIpSource: string; networkIpCertainty: string
  networkLocation: string; networkLocationSource: string; networkLocationCertainty: string
  networkOrg: string; networkOrgSource: string; networkOrgCertainty: string
  greenSize: string; greenSizeDesc: string; greenHosting: string; greenHostingDesc: string; greenCarbon: string; greenCarbonDesc: string
  sec1Desc: string; sec2Desc: string; sec3Desc: string
}> = {
  tr: { homeBoundaryText: "Headerly, isteğinizde görünen teknik bilgileri açıklamaya çalışır. IP konumu yaklaşık olabilir; User-Agent kesin bir kimlik değildir; güvenlik ve karbon sonuçları sınırlı sinyallere dayanır.", homeHow: "Headerly nasıl çalışır?", homePrivacy: "Gizlilik açıklamasını okuyun", networkIp: "IP adresi", networkIpSource: "Proxy / sunucu isteği", networkIpCertainty: "İstek açısından yüksek", networkLocation: "Ülke ve şehir", networkLocationSource: "CDN edge metadatası", networkLocationCertainty: "Yaklaşık", networkOrg: "ISP / organizasyon", networkOrgSource: "ASN veya sağlayıcı bilgisi", networkOrgCertainty: "Değişebilir", greenSize: "Yanıt boyutu", greenSizeDesc: "Sunucudan indirilen ilk yanıtın boyutu.", greenHosting: "Hosting sinyali", greenHostingDesc: "Alan adı için Green Web Foundation kaydı.", greenCarbon: "Karbon tahmini", greenCarbonDesc: "Boyut ve hosting sinyalinden türetilen yaklaşık değer; tam karbon ayak izi değildir.", sec1Desc: "Araç, hedef URL’nin response header’larını okur; kaynak kodunu veya tüm açıkları incelemez.", sec2Desc: "Kontroller uygun, incelenmeli veya bulunamadı olarak gösterilir. Bulunamadı her zaman açık değildir.", sec3Desc: "Öneriyi uyguladıktan sonra sonucu yeniden çalıştırın ve kendi kullanım senaryonuzla değerlendirin." },
  en: { homeBoundaryText: "Headerly explains technical signals visible in your request. IP location can be approximate; a User-Agent is not a verified identity; security and carbon results cover limited signals.", homeHow: "How Headerly works", homePrivacy: "Read the privacy explanation", networkIp: "IP address", networkIpSource: "Proxy / server request", networkIpCertainty: "High for this request", networkLocation: "Country and city", networkLocationSource: "CDN edge metadata", networkLocationCertainty: "Approximate", networkOrg: "ISP / organization", networkOrgSource: "ASN or provider data", networkOrgCertainty: "May vary", greenSize: "Response size", greenSizeDesc: "Size of the first response downloaded from the server.", greenHosting: "Hosting signal", greenHostingDesc: "Whether the domain has a Green Web Foundation record.", greenCarbon: "Carbon estimate", greenCarbonDesc: "An approximation derived from size and hosting; not a full carbon footprint.", sec1Desc: "The tool reads response headers from the target URL; it does not inspect source code or every application vulnerability.", sec2Desc: "Checks are shown as appropriate, review, or not found. Not found does not always mean a vulnerability.", sec3Desc: "Apply a recommendation, run the check again, and interpret it in your own context." },
  de: { homeBoundaryText: "Headerly erklärt technische Signale, die in Ihrer Anfrage sichtbar sind. Die IP-Ortung kann ungenau sein; ein User-Agent ist keine bestätigte Identität; Sicherheits- und CO₂-Ergebnisse decken nur begrenzte Signale ab.", homeHow: "So funktioniert Headerly", homePrivacy: "Datenschutzerklärung lesen", networkIp: "IP-Adresse", networkIpSource: "Proxy-/Server-Anfrage", networkIpCertainty: "Für diese Anfrage hoch", networkLocation: "Land und Stadt", networkLocationSource: "CDN-Edge-Metadaten", networkLocationCertainty: "Ungefähr", networkOrg: "ISP / Organisation", networkOrgSource: "ASN- oder Anbieterangaben", networkOrgCertainty: "Kann abweichen", greenSize: "Antwortgröße", greenSizeDesc: "Größe der ersten vom Server geladenen Antwort.", greenHosting: "Hosting-Signal", greenHostingDesc: "Ob für die Domain ein Eintrag bei der Green Web Foundation vorhanden ist.", greenCarbon: "CO₂-Schätzung", greenCarbonDesc: "Eine Näherung aus Größe und Hosting, keine vollständige CO₂-Bilanz.", sec1Desc: "Das Werkzeug liest die Response-Header der Ziel-URL; Quellcode und alle Schwachstellen werden nicht geprüft.", sec2Desc: "Prüfungen werden als geeignet, prüfen oder nicht gefunden angezeigt. Nicht gefunden bedeutet nicht immer eine Schwachstelle.", sec3Desc: "Wenden Sie eine Empfehlung an, führen Sie die Prüfung erneut aus und bewerten Sie sie im eigenen Kontext." },
  es: { homeBoundaryText: "Headerly explica las señales técnicas visibles en tu solicitud. La ubicación por IP puede ser aproximada; un User-Agent no es una identidad verificada; los resultados de seguridad y carbono cubren señales limitadas.", homeHow: "Cómo funciona Headerly", homePrivacy: "Leer la explicación de privacidad", networkIp: "Dirección IP", networkIpSource: "Solicitud del proxy / servidor", networkIpCertainty: "Alta para esta solicitud", networkLocation: "País y ciudad", networkLocationSource: "Metadatos del edge del CDN", networkLocationCertainty: "Aproximada", networkOrg: "ISP / organización", networkOrgSource: "Datos de ASN o proveedor", networkOrgCertainty: "Puede variar", greenSize: "Tamaño de la respuesta", greenSizeDesc: "Tamaño de la primera respuesta descargada del servidor.", greenHosting: "Señal de hosting", greenHostingDesc: "Si el dominio tiene un registro en Green Web Foundation.", greenCarbon: "Estimación de carbono", greenCarbonDesc: "Aproximación basada en el tamaño y el hosting; no es una huella completa.", sec1Desc: "La herramienta lee las cabeceras de respuesta de la URL; no revisa el código fuente ni todas las vulnerabilidades.", sec2Desc: "Los controles aparecen como correcto, revisar o no encontrado. No encontrado no siempre significa una vulnerabilidad.", sec3Desc: "Aplica una recomendación, repite la comprobación y evalúala según tu contexto." },
  fr: { homeBoundaryText: "Headerly explique les signaux techniques visibles dans votre requête. La localisation par IP peut être approximative ; un User-Agent n’est pas une identité vérifiée ; les résultats de sécurité et de carbone couvrent des signaux limités.", homeHow: "Comment fonctionne Headerly", homePrivacy: "Lire l’explication sur la confidentialité", networkIp: "Adresse IP", networkIpSource: "Requête du proxy / serveur", networkIpCertainty: "Élevée pour cette requête", networkLocation: "Pays et ville", networkLocationSource: "Métadonnées de l’edge CDN", networkLocationCertainty: "Approximative", networkOrg: "FAI / organisation", networkOrgSource: "Données ASN ou fournisseur", networkOrgCertainty: "Variable", greenSize: "Taille de la réponse", greenSizeDesc: "Taille de la première réponse téléchargée depuis le serveur.", greenHosting: "Signal d’hébergement", greenHostingDesc: "Présence d’un enregistrement Green Web Foundation pour le domaine.", greenCarbon: "Estimation carbone", greenCarbonDesc: "Approximation fondée sur la taille et l’hébergement, pas une empreinte complète.", sec1Desc: "L’outil lit les en-têtes de réponse de l’URL ; il n’examine ni le code source ni toutes les vulnérabilités.", sec2Desc: "Les contrôles sont indiqués comme corrects, à examiner ou introuvables. Introuvable ne signifie pas toujours vulnérabilité.", sec3Desc: "Appliquez une recommandation, relancez le contrôle et interprétez-le selon votre contexte." },
  hi: { homeBoundaryText: "Headerly आपके अनुरोध में दिखने वाले तकनीकी संकेतों को समझाता है। IP स्थान अनुमानित हो सकता है; User-Agent सत्यापित पहचान नहीं है; सुरक्षा और कार्बन परिणाम सीमित संकेतों तक हैं।", homeHow: "Headerly कैसे काम करता है", homePrivacy: "गोपनीयता विवरण पढ़ें", networkIp: "IP पता", networkIpSource: "Proxy / सर्वर अनुरोध", networkIpCertainty: "इस अनुरोध के लिए उच्च", networkLocation: "देश और शहर", networkLocationSource: "CDN edge मेटाडेटा", networkLocationCertainty: "अनुमानित", networkOrg: "ISP / संगठन", networkOrgSource: "ASN या प्रदाता डेटा", networkOrgCertainty: "बदल सकता है", greenSize: "Response का आकार", greenSizeDesc: "सर्वर से डाउनलोड किए गए पहले response का आकार।", greenHosting: "Hosting संकेत", greenHostingDesc: "क्या domain का Green Web Foundation में रिकॉर्ड है।", greenCarbon: "कार्बन अनुमान", greenCarbonDesc: "आकार और hosting से निकला अनुमान; पूरा carbon footprint नहीं।", sec1Desc: "यह टूल target URL के response headers पढ़ता है; source code या सभी vulnerabilities की जाँच नहीं करता।", sec2Desc: "Checks को उचित, समीक्षा करें या नहीं मिला के रूप में दिखाया जाता है। नहीं मिला हमेशा vulnerability नहीं होता।", sec3Desc: "सुझाव लागू करें, जाँच फिर चलाएँ और अपने context में परिणाम समझें।" },
  zh: { homeBoundaryText: "Headerly 用于解释请求中可见的技术信号。IP 定位可能只是近似值；User-Agent 不是经过验证的身份；安全和碳排结果只覆盖有限信号。", homeHow: "Headerly 的工作方式", homePrivacy: "阅读隐私说明", networkIp: "IP 地址", networkIpSource: "代理 / 服务器请求", networkIpCertainty: "对本次请求较确定", networkLocation: "国家和城市", networkLocationSource: "CDN 边缘元数据", networkLocationCertainty: "近似值", networkOrg: "ISP / 组织", networkOrgSource: "ASN 或提供商数据", networkOrgCertainty: "可能变化", greenSize: "响应大小", greenSizeDesc: "从服务器下载的第一个响应的大小。", greenHosting: "托管信号", greenHostingDesc: "该域名是否在 Green Web Foundation 中有记录。", greenCarbon: "碳排估算", greenCarbonDesc: "根据大小和托管信号得出的近似值，不是完整碳足迹。", sec1Desc: "工具读取目标 URL 的 response headers，不检查源代码或所有应用漏洞。", sec2Desc: "检查结果显示为合适、需复核或未找到。未找到不一定表示存在漏洞。", sec3Desc: "应用建议后重新检查，并结合自己的使用场景解读结果。" }
}
